### PR TITLE
Convert Union Types to Enums

### PR DESCRIPTION
**Pull request by FailedChecksum**
Proposition to convert string Union Types to StringEnums

### CODE REVIEW

**Comment by dr010001111** [comment]
Could you convert them to use PascalCase instead? Thanks.

EditorConfig added!

**Comment by FailedChecksum** [comment]
@dr010001111 
- fixed
- added TSLint since that convention conflicts with the linter defaults (style warnings now included, see image)
- added additional package with common naming-conventions lint support

image

**Comment by dr010001111** [comment]
@FailedChecksum TSLint is deprecated, see https://github.com/palantir/tslint/issues/4534

Added ESLint \w TypeScript plugins. Also did some cleanup, I've applied your changes as patch, thanks!

Take a look over 3d7760cddd54432dce1893c15259588149813f79 and confirm changes.
Closing if no other remarks added.

**Comment by FailedChecksum** [comment]
Looks good to me. 

Note on OS etiquette: Avoid reauthoring, as it can discourage OS contribution.

I don't mind in this case because I was being sloppy :rofl: 

Closing.

**Pull request closed without merging**
